[streamers."zhan |"]
url = ["https://live.bilibili.com/173469252"]
tags = ["biliup"]

[streamers."马统君-"]
url = ["https://live.bilibili.com/27829976"]
tags = ["biliup"]

[streamers."高子巷"]
url = ["https://live.bilibili.com/3493113414814567"]
tags = ["biliup"]

